$schema: "./settings.schema.yaml"
# ---------- Application settings ----- #
environment: development

scenes:
  - scene_id: "university-floor-1"
    svg_file: "university-floor-1.svg"
    title: "Floor 1"
    legend:
      - legend_id: "Reception"
        color: "#ffe302"
      - legend_id: "Cloakroom"
        color: "#91a3b0"
      - legend_id: "Elevator"
        color: "#17b69c"
      - legend_id: "Dining area"
        color: "#9adbf8"
      - legend_id: "Lecture hall"
        color: "#b3dd36"
      - legend_id: "Applicant reception"
        color: "#2d4485"
      - legend_id: "Storage"
        color: "#ffcb7d"
      - legend_id: "Psychologist"
        color: "#f89aef"
      - legend_id: "Medical point — 1st floor of 4th campus"
    areas:
      - title: "1.1"
        svg_polygon_id: "1.1"
      - title: "1.2"
        svg_polygon_id: "1.2"
      - title: "101"
        svg_polygon_id: "101"
      - title: "102"
        svg_polygon_id: "102"
      - title: "103"
        svg_polygon_id: "103"
      - title: "104"
        svg_polygon_id: "104"
      - title: "105"
        svg_polygon_id: "105"
      - title: "106"
        svg_polygon_id: "106"
      - title: "107"
        svg_polygon_id: "107"
      - title: "108"
        svg_polygon_id: "108"
      - title: "109"
        svg_polygon_id: "109"
      - title: "110"
        svg_polygon_id: "110"
      - title: "111"
        svg_polygon_id: "111"
      - title: "112"
        svg_polygon_id: "112"
      - title: "113"
        svg_polygon_id: "113"
      - title: "114"
        svg_polygon_id: "114"
      - title: Canteen
        svg_polygon_id: canteen
      - title: Cava
        svg_polygon_id: cava
      - title: Coffee-in
        svg_polygon_id: coffee-in
      - title: Coffee++
        svg_polygon_id: coffee-plus-plus
      - title: Garage (entrance is on -1 floor)
        svg_polygon_id: garage-1
      - title: Reading Hall
        svg_polygon_id: reading-hall-1
      - title: Wrap & Go
        svg_polygon_id: wrap-n-go
  - scene_id: "university-floor-2"
    svg_file: "university-floor-2.svg"
    title: "Floor 2"
    legend:
      - legend_id: "Elevator"
        color: "#17b69c"
      - legend_id: "Lecture hall"
        color: "#b3dd36"
      - legend_id: "Meeting rooms"
        color: "#9681f2"
      - legend_id: "Personnel and Corporate Culture Development Center"
        color: "#dd7168"
    areas:
      - title: "105"
        svg_polygon_id: "105"
      - title: "106"
        svg_polygon_id: "106"
      - title: "107"
        svg_polygon_id: "107"
      - title: "108"
        svg_polygon_id: "108"
      - title: "2.1"
        svg_polygon_id: "2.1"
      - title: "2.2"
        svg_polygon_id: "2.2"
      - title: "2.3"
        svg_polygon_id: "2.3"
      - title: "2.4"
        svg_polygon_id: "2.4"
      - title: "201"
        svg_polygon_id: "201"
      - title: "202"
        svg_polygon_id: "202"
      - title: "203"
        svg_polygon_id: "203"
      - title: "204"
        svg_polygon_id: "204"
      - title: "205"
        svg_polygon_id: "205"
      - title: "206"
        svg_polygon_id: "206"
      - title: "207"
        svg_polygon_id: "207"
      - title: "208"
        svg_polygon_id: "208"
      - title: "209"
        svg_polygon_id: "209"
      - title: "210"
        svg_polygon_id: "210"
      - title: "210a"
        svg_polygon_id: "210a"
      - title: "211"
        svg_polygon_id: "211"
      - title: "212"
        svg_polygon_id: "212"
      - title: "212a"
        svg_polygon_id: "212a"
      - title: "213"
        svg_polygon_id: "213"
      - title: canteen-2
        svg_polygon_id: canteen-2
      - title: garage-2
        svg_polygon_id: garage-2
      - title: reading-hall-2
        svg_polygon_id: reading-hall-2
  - scene_id: "university-floor-3"
    svg_file: "university-floor-3.svg"
    title: "Floor 3"
    legend:
      - legend_id: "Elevator"
        color: "#9681f2"
      - legend_id: "Dining area"
        color: "#9adbf8"
      - legend_id: "Meeting rooms"
        color: "#9681f2"
    areas:
      - title: "3.1"
        svg_polygon_id: "3.1"
      - title: "3.2"
        svg_polygon_id: "3.2"
      - title: "3.3"
        svg_polygon_id: "3.3"
      - title: "3.4"
        svg_polygon_id: "3.4"
      - title: "3.5"
        svg_polygon_id: "3.5"
      - title: "300"
        svg_polygon_id: "300"
      - title: "301"
        svg_polygon_id: "301"
      - title: "302"
        svg_polygon_id: "302"
      - title: "303"
        svg_polygon_id: "303"
      - title: "304"
        svg_polygon_id: "304"
      - title: "305"
        svg_polygon_id: "305"
      - title: "306"
        svg_polygon_id: "306"
      - title: "306a"
        svg_polygon_id: "306a"
      - title: "307"
        svg_polygon_id: "307"
      - title: "308"
        svg_polygon_id: "308"
      - title: "309"
        svg_polygon_id: "309"
      - title: "309a"
        svg_polygon_id: "309a"
      - title: "310"
        svg_polygon_id: "310"
      - title: "310a"
        svg_polygon_id: "310a"
      - title: "311"
        svg_polygon_id: "311"
      - title: "311a"
        svg_polygon_id: "311a"
      - title: "312"
        svg_polygon_id: "312"
      - title: "312a"
        svg_polygon_id: "312a"
      - title: "313"
        svg_polygon_id: "313"
      - title: "314"
        svg_polygon_id: "314"
      - title: "315"
        svg_polygon_id: "315"
      - title: "316"
        svg_polygon_id: "316"
      - title: "317"
        svg_polygon_id: "317"
      - title: "318"
        svg_polygon_id: "318"
      - title: "319"
        svg_polygon_id: "319"
      - title: "320"
        svg_polygon_id: "320"
      - title: "321"
        svg_polygon_id: "321"
      - title: "322"
        svg_polygon_id: "322"
      - title: Canteen
        svg_polygon_id: canteen-3
      - title: Reading Hall
        svg_polygon_id: reading-hall-3
  - scene_id: "university-floor-4"
    svg_file: "university-floor-4.svg"
    title: "Floor 4"
    legend:
      - legend_id: "Elevator"
        color: "#17b69c"
      - legend_id: "Coffice"
        color: "#9adbf8"
      - legend_id: "Meeting rooms"
        color: "#9681f2"
      - legend_id: "IT Equipment Storage"
        color: "#ffcb7d"
      - legend_id: "Administration"
        color: "#6d9bde"
        legend: "423 — Rector's office\n424 — Director's office"
      - legend_id: "Recruitment"
        color: "#de766d"
        legend: "433 — Recruitment sector\n455 — Human  resources department"
    areas:
      - title: "4.2"
        svg_polygon_id: "4.2"
      - title: "4.3"
        svg_polygon_id: "4.3"
      - title: "4.4"
        svg_polygon_id: "4.4"
      - title: "4.5"
        svg_polygon_id: "4.5"
      - title: "401"
        svg_polygon_id: "401"
      - title: "402"
        svg_polygon_id: "402"
      - title: "403"
        svg_polygon_id: "403"
      - title: "404"
        svg_polygon_id: "404"
      - title: "405"
        svg_polygon_id: "405"
      - title: "406"
        svg_polygon_id: "406"
      - title: "407"
        svg_polygon_id: "407"
      - title: "408"
        svg_polygon_id: "408"
      - title: "409"
        svg_polygon_id: "409"
      - title: "410"
        svg_polygon_id: "410"
      - title: "411"
        svg_polygon_id: "411"
      - title: "411a"
        svg_polygon_id: "411a"
      - title: "412"
        svg_polygon_id: "412"
      - title: "413"
        svg_polygon_id: "413"
      - title: "414"
        svg_polygon_id: "414"
      - title: "415"
        svg_polygon_id: "415"
      - title: "416"
        svg_polygon_id: "416"
      - title: "417"
        svg_polygon_id: "417"
      - title: "418"
        svg_polygon_id: "418"
      - title: "419"
        svg_polygon_id: "419"
      - title: "420"
        svg_polygon_id: "420"
      - title: "421"
        svg_polygon_id: "421"
      - title: "422"
        svg_polygon_id: "422"
      - title: "423"
        svg_polygon_id: "423"
      - title: "424"
        svg_polygon_id: "424"
      - title: "425"
        svg_polygon_id: "425"
      - title: "426"
        svg_polygon_id: "426"
      - title: "427"
        svg_polygon_id: "427"
      - title: "428"
        svg_polygon_id: "428"
      - title: "429"
        svg_polygon_id: "429"
      - title: "430"
        svg_polygon_id: "430"
      - title: "431"
        svg_polygon_id: "431"
      - title: "432"
        svg_polygon_id: "432"
      - title: "433"
        svg_polygon_id: "433"
      - title: "434"
        svg_polygon_id: "434"
      - title: "435"
        svg_polygon_id: "435"
      - title: "436"
        svg_polygon_id: "436"
      - title: "437"
        svg_polygon_id: "437"
      - title: "438"
        svg_polygon_id: "438"
      - title: "439"
        svg_polygon_id: "439"
      - title: "440"
        svg_polygon_id: "440"
      - title: "441"
        svg_polygon_id: "441"
      - title: "442"
        svg_polygon_id: "442"
      - title: "443a"
        svg_polygon_id: "443a"
      - title: "443b"
        svg_polygon_id: "443b"
      - title: "443c"
        svg_polygon_id: "443c"
      - title: "444"
        svg_polygon_id: "444"
      - title: "445"
        svg_polygon_id: "445"
      - title: "446"
        svg_polygon_id: "446"
      - title: "446a"
        svg_polygon_id: "446a"
      - title: "447"
        svg_polygon_id: "447"
      - title: "448"
        svg_polygon_id: "448"
      - title: "449"
        svg_polygon_id: "449"
      - title: "450"
        svg_polygon_id: "450"
      - title: "450a"
        svg_polygon_id: "450a"
      - title: "451"
        svg_polygon_id: "451"
      - title: "452"
        svg_polygon_id: "452"
      - title: "453"
        svg_polygon_id: "453"
      - title: "454"
        svg_polygon_id: "454"
      - title: "455"
        svg_polygon_id: "455"
      - title: "456"
        svg_polygon_id: "456"
      - title: "457"
        svg_polygon_id: "457"
      - title: "458"
        svg_polygon_id: "458"
      - title: "459"
        svg_polygon_id: "459"
      - title: "460"
        svg_polygon_id: "460"
      - title: "461"
        svg_polygon_id: "461"
      - title: "462"
        svg_polygon_id: "462"
      - title: "463"
        svg_polygon_id: "463"
      - title: "464"
        svg_polygon_id: "464"
      - title: "465"
        svg_polygon_id: "465"
      - title: "466"
        svg_polygon_id: "466"
      - title: "467"
        svg_polygon_id: "467"
      - title: "468"
        svg_polygon_id: "468"
      - title: "469"
        svg_polygon_id: "469"
      - title: "470"
        svg_polygon_id: "470"
      - title: "471"
        svg_polygon_id: "471"
      - title: "472"
        svg_polygon_id: "472"
      - title: "473"
        svg_polygon_id: "473"
      - title: "474"
        svg_polygon_id: "474"
      - title: "475"
        svg_polygon_id: "475"
      - title: "476"
        svg_polygon_id: "476"

  - scene_id: "university-floor-5"
    svg_file: "university-floor-5.svg"
    title: "Floor 5"
    legend:
      - legend_id: "Elevator"
        color: "#17b69c"
      - legend_id: "504B — Library"
    areas:
      - title: "501"
        svg_polygon_id: "501"
      - title: "502a"
        svg_polygon_id: "502a"
      - title: "502b"
        svg_polygon_id: "502b"
      - title: "503"
        svg_polygon_id: "503"
      - title: "504a"
        svg_polygon_id: "504a"
      - title: "504b"
        svg_polygon_id: "504b"
      - title: "504c"
        svg_polygon_id: "504c"
      - title: "505"
        svg_polygon_id: "505"
      - title: "506"
        svg_polygon_id: "506"
      - title: "507"
        svg_polygon_id: "507"
      - title: "508"
        svg_polygon_id: "508"
      - title: "509"
        svg_polygon_id: "509"
      - title: "510"
        svg_polygon_id: "510"
      - title: "511"
        svg_polygon_id: "511"
      - title: "512"
        svg_polygon_id: "512"
      - title: "513"
        svg_polygon_id: "513"
      - title: "514"
        svg_polygon_id: "514"
      - title: "515"
        svg_polygon_id: "515"
      - title: "516"
        svg_polygon_id: "516"

  - scene_id: "university-floor-0"
    svg_file: "university-floor-0.svg"
    title: "Floor -1"
    legend:
      - legend_id: "Elevator"
        color: "#17b69c"
    areas:
      - title: "105a"
        svg_polygon_id: "105a"
      - title: Garage
        svg_polygon_id: garage-0
