$schema: https://json-schema.org/draft-07/schema
$defs:
  Accounts:
    additionalProperties: false
    description: InNoHassle Accounts integration settings
    properties:
      api_url:
        default: https://api.innohassle.ru/accounts/v0
        description: URL of the Accounts API
        title: Api Url
        type: string
    title: Accounts
    type: object
  Environment:
    enum:
    - development
    - production
    title: Environment
    type: string
additionalProperties: false
description: Settings for the application.
properties:
  $schema:
    default: null
    title: $Schema
    type: string
  environment:
    $ref: '#/$defs/Environment'
    default: development
    description: App environment flag
  app_root_path:
    default: ''
    description: Prefix for the API path (e.g. "/api/v0")
    title: App Root Path
    type: string
  cors_allow_origin_regex:
    default: .*
    description: 'Allowed origins for CORS: from which domains requests to the API
      are allowed.

      Specify as a regex: `https://.*.innohassle.ru`'
    title: Cors Allow Origin Regex
    type: string
  static_mount_path:
    default: /static
    description: Path to mount static files
    title: Static Mount Path
    type: string
  static_directory:
    default: static
    description: Path to the directory with static files
    format: path
    title: Static Directory
    type: string
  accounts:
    $ref: '#/$defs/Accounts'
    default:
      api_url: https://api.innohassle.ru/accounts/v0
    description: InNoHassle-Accounts integration settings
title: Settings
type: object
