$schema: https://json-schema.org/draft-07/schema
$defs:
  Accounts:
    additionalProperties: false
    description: InNoHassle Accounts integration settings
    properties:
      api_url:
        default: https://api.innohassle.ru/accounts/v0
        description: URL of the Accounts API
        title: Api Url
        type: string
    title: Accounts
    type: object
  Area:
    additionalProperties: false
    properties:
      svg_polygon_id:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        description: ID of the polygon in the SVG
        title: Svg Polygon Id
      title:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        description: Title of the area
        title: Title
      ru_title:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        description: Title in Russian
        title: Ru Title
      legend_id:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        description: ID of the legend (if any)
        title: Legend Id
      description:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        description: Description of the area
        title: Description
      people:
        default: []
        description: List of people for this area
        items:
          type: string
        title: People
        type: array
      prioritized:
        default: false
        description: Priority for multi-floor areas
        title: Prioritized
        type: boolean
    title: Area
    type: object
  Environment:
    enum:
    - development
    - production
    title: Environment
    type: string
  LegendEntry:
    additionalProperties: false
    properties:
      legend_id:
        description: ID of the legend
        title: Legend Id
        type: string
      color:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        description: Color of the legend
        title: Color
      legend:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        description: Description of the legend (may contain multiple lines)
        title: Legend
    required:
    - legend_id
    title: LegendEntry
    type: object
  Scene:
    additionalProperties: false
    properties:
      scene_id:
        description: ID of the scene
        title: Scene Id
        type: string
      title:
        description: Title of the scene
        title: Title
        type: string
      svg_file:
        description: Path to the SVG file in /static
        title: Svg File
        type: string
      legend:
        default: []
        description: Legend of the scene
        items:
          $ref: '#/$defs/LegendEntry'
        title: Legend
        type: array
      areas:
        default: []
        description: Areas of the scene
        items:
          $ref: '#/$defs/Area'
        title: Areas
        type: array
    required:
    - scene_id
    - title
    - svg_file
    title: Scene
    type: object
additionalProperties: false
description: Settings for the application.
properties:
  $schema:
    default: null
    title: $Schema
    type: string
  environment:
    $ref: '#/$defs/Environment'
    default: development
    description: App environment flag
  app_root_path:
    default: ''
    description: Prefix for the API path (e.g. "/api/v0")
    title: App Root Path
    type: string
  scenes:
    default: []
    description: List of scenes
    items:
      $ref: '#/$defs/Scene'
    title: Scenes
    type: array
  cors_allow_origin_regex:
    default: .*
    description: 'Allowed origins for CORS: from which domains requests to the API
      are allowed.

      Specify as a regex: `https://.*.innohassle.ru`'
    title: Cors Allow Origin Regex
    type: string
  static_mount_path:
    default: /static
    description: Path to mount static files
    title: Static Mount Path
    type: string
  static_directory:
    default: static
    description: Path to the directory with static files
    format: path
    title: Static Directory
    type: string
  accounts:
    $ref: '#/$defs/Accounts'
    default:
      api_url: https://api.innohassle.ru/accounts/v0
    description: InNoHassle-Accounts integration settings
title: Settings
type: object
