$schema: "./settings.schema.yaml"
# ---------- Application settings ----- #
environment: development

scenes:
  - scene_id: "university-floor-1"
    svg_file: "university-floor-1.svg"
    title: "Floor 1"
    areas:
      - title: "108"
      - title: "107"
    legend:
      - legend_id: "Reception"
        color: "#ffe302"
      - legend_id: "Cloakroom"
        color: "#91a3b0"
      - legend_id: "Elevator"
        color: "#17b69c"
      - legend_id: "Dining area"
        color: "#9adbf8"
      - legend_id: "Lecture hall"
        color: "#b3dd36"
      - legend_id: "Applicant reception"
        color: "#2d4485"
      - legend_id: "Storage"
        color: "#ffcb7d"
      - legend_id: "Psychologist"
        color: "#f89aef"
      - legend_id: "Medical point — 1st floor of 4th campus"
  - scene_id: "university-floor-2"
    svg_file: "university-floor-2.svg"
    title: "Floor 2"
    legend:
      - legend_id: "Elevator"
        color: "#17b69c"
      - legend_id: "Lecture hall"
        color: "#b3dd36"
      - legend_id: "Meeting rooms"
        color: "#9681f2"
      - legend_id: "Personnel and Corporate Culture Development Center"
        color: "#dd7168"
  - scene_id: "university-floor-3"
    svg_file: "university-floor-3.svg"
    title: "Floor 3"
    areas:
      - title: "314"
    legend:
      - legend_id: "Elevator"
        color: "#9681f2"
      - legend_id: "Dining area"
        color: "#9adbf8"
      - legend_id: "Meeting rooms"
        color: "#9681f2"
  - scene_id: "university-floor-4"
    svg_file: "university-floor-4.svg"
    title: "Floor 4"
    legend:
      - legend_id: "Elevator"
        color: "#17b69c"
      - legend_id: "Coffice"
        color: "#9adbf8"
      - legend_id: "Meeting rooms"
        color: "#9681f2"
      - legend_id: "IT Equipment Storage"
        color: "#ffcb7d"
      - legend_id: "Administration"
        color: "#6d9bde"
        description: "423 — Rector's office\n424 — Director's office"
      - legend_id: "Recruitment"
        color: "#de766d"
        description: "433 — Recruitment sector\n455 — Human  resources department"
  - scene_id: "university-floor-5"
    svg_file: "university-floor-5.svg"
    title: "Floor 5"
    legend:
      - legend_id: "Elevator"
        color: "#17b69c"
      - legend_id: "504B — Library"
  - scene_id: "university-floor-0"
    svg_file: "university-floor-0.svg"
    title: "Floor -1"
    legend:
      - legend_id: "Elevator"
        color: "#17b69c"
